= Dinâmicas de Grupo categorizadas
v1.0, 01/2019
:toc: left
:toclevels: 1
:doctype: book

= Descontração

[partintro]
--
This is the introduction to the first part of our mud-encrusted journey.
--

== 21. Dinâmica: Sorriso Milionário

Objetivo:: Descontração

Material:: bolinhas de papel amassado

=== Procedimento

Essa dinâmica é usada para descontrair e integrar o grupo de uma forma divertida. Cada bolinha vale R$1.000,00. O professor distribuirá para cada pessoa do grupo 5 bolinhas de papel, essas deverão estar dispersas no local onde será realizada a brincadeira. Dado o sinal os alunos deverão sair e procurar um companheiro, em seguida devem parar em sua frente, olhar fixamente nos olhos desse companheiro que por sua vez não pode sorrir. Quem sorrir primeiro paga uma bolinha para a pessoa a quem sorriu. Vence quem terminar a brincadeira com mais "dinheiro", que será o milionário.

== 37. Dinâmica: "do papel"

Objetivo:: Descontração

Materiais:: pedaço de papel, caneta

=== Procedimento

Forma-se um círculo e em seguida será distribuído um pedaço de papel para
cada um, e uma caneta. Logo após a pessoa irá escrever qualquer pergunta que ela quiser, ex: Porque hoje fez sol? entendeu?!É qualquer pergunta, o que vier na cabeça. Ai logo após
o instrutor irá pegar os papéis de todos os participantes, embaralhar e entregar um para
cada (só que você não poderá pegar o seu), ai depois de feito isso a pessoa vai responder o
que estiver naquele papel que ela pegou. Depois que todos responderem sem um ver o do
outro, você vai dobrar seu papel e vai passar 2 vezes para seu lado direito todos juntos. Ai
começa a brincadeira. Uma pessoa começa lendo o que está em seu papel, em seguida a
pessoa do lado direito ou esquerdo (depende do monitor escolher), digamos que foi pela
direita, ai a pessoa vai ler o que está escrito na RESPOSTA dela, e assim sucessivamente, a
mesma que respondeu a resposta vai ler a sua pergunta e o vizinho ao lado responderá a
sua resposta é muito legal e divertindo causando muitos risos!!!!
